### ISSUE TITLE
Possibly different coverages between the CPRBB website and OpenAQ

### ISSUE THREAD

**Issue by maelle** [hks-epod/indiaspend-pollution-data#1]
In reference to this issue https://github.com/openaq/openaq-api/issues/167

and to my code here https://github.com/masalmon/Ropenaq/blob/master/develop/finding_proportion_missing.R

I have the impression that one gets e.g. data for RK Puram on the 15th of December last year from Open AQ (see the interface here http://dolugen.github.io/openaq-browser/#/measurements ) which the Central Pollution Control Board (CPCB) website does not have.

Does this mean the monitor downtime is not really one? (or I might be missing something essential here, so correct me if I do!)

**Comment by edodge** [comment]
Do we know where openaq is pulling their data from? My results come from a scrape of the CPCB portal. The DPCC portal also does not have results for RK Puram on December 15 (the CPCB portal is supposed to have everything for both the CPCB and DPCC monitors in Delhi).

**Comment by maelle** [comment]
@jflasher could you answer?

**Comment by jflasher** [comment]
You can see where the Indian data is come from at https://github.com/openaq/openaq-fetch/blob/master/sources/in.json. Looks like it's coming from DPCC. We get it in real time, so there may be a difference between getting it in real-time and getting it historically?

**Comment by maelle** [comment]
This would mean that the monitor was not down but that data were lost? Not on purpose I hope. 

I/ssomeone else should compare the time series from the two sources. ☺

**Comment by edodge** [comment]
Interesting. Perhaps part of the <a href="http://articles.economictimes.indiatimes.com/2015-03-11/news/60008356_1_air-quality-monitoring-dpcc">"data validation"</a> process?

I would be very interested to see if the readings that go missing are higher on average than other readings at the same monitor, or if they have some characteristics that imply something is going wrong with the monitor. The latter case would be a reasonable justification for getting rid of them.

**Comment by maelle** [comment]
Yep exactly. Is it easy for you to output the time series for Delhi from the website? I would easily upload the openaq ones (in a few hours).

**Comment by maelle** [comment]
For locations available in openaq, that is.

**Comment by edodge** [comment]
Can you use the data in "indiaspend-pollution-data/monitors/data prep/input/cpcb_ambient_panel.csv"? I'd rather not share more than that at the moment since crawling the very slow CPCB website took several months.

**Comment by maelle** [comment]
Ok! I know this website, which is why I love openaq. Will keep you both updated when I make the comparison!

**Comment by maelle** [comment]
Everything is now here https://github.com/masalmon/RealTimeVsHistoric (R code, two csv files, pictures). 
I'm a bad person and did not write a legend on the graph (and now I want to stop working :-) ):
- blue=historic values
- purple=OpenAQ

I plotted values only for the dates that both files had in common (OpenAQ started recording the values in June).
It does not look like data cleaning to me, well not only. For Punjabi Bagh there are not historic data from the CPCB website since May but there are OpenAQ values. I find it very interesting!
I can answer any question tomorrow my time, or make the analysis somewhat easier to read (making a html out of it using RMarkdown).

@jflasher I have a question regarding the time recorded by OpenAQ. It is the time at which OpenAQ did the query rather than the time at which a value was published by the source, or is it the time at which the value was published?

I wish both of you a nice start in the week-end!

**Comment by jflasher** [comment]
Awesome @masalmon! The time we save is the time the source says the data is from. So this is not necessarily the time it was published or the time we queried.

**Comment by maelle** [comment]
With an example such as Punjabi Bagh you can really say Open AQ saves data from oblivion! :-)

**Comment by edodge** [comment]
I snapped my datetimes to the nearest 15 minute mark (:00, :15, :30, :45) so there will be some slight discrepancies between what's in my .csv and what's on the CPCB portal.

**Comment by edodge** [comment]
Now the question is how long those readings stay up on the portal.

**Comment by jflasher** [comment]
I believe we've seen issues where the same number might be reported for several 'intervals'. Same physical value but different time interval. We only capture one record for a given time, no matter how long it's up there, if that makes sense. It shows up as plateaus in a graph of our data. Could be physically meaningful or indicative of repeated data.

**Comment by maelle** [comment]
i've done better graphics that show holes in OpenAQ data too actually, and I limited the graphs until November which somehow I hadn't succeeded in doing yesterday. Still here https://github.com/masalmon/RealTimeVsHistoric/

What happened with Punjabi Bagh data? That's weird.

Regarding gaps in OpenAQ data, what can they be due to?

**Comment by maelle** [comment]
I added a pdf, html and docx version of the analysis in the repository.

@edodge I have two questions.
1) Do you think it is possible that the other monitors from your figure in India Spend that are white at the end of the year were not down but had the same fate as Punjabi Bagh (data not published)?
2) Would having more data changed your analysis of the odd/even plan? (this http://indianexpress.com/article/opinion/columns/odd-even-policy-delhi-pollution-yes-delhi-it-worked/ )

**Comment by maelle** [comment]
@edodge, is it possible you have "1" for monitor reading but no value? E.g. RK Puram 4th april, 13:00 to 13:30 (although for hourly data it is not bad I guess :-) )

(I'm looking at the two data tables in Excel, no shame :-) )

**Comment by maelle** [comment]
How exactly did you do the web-scraping? I'm fascinated because the website is tricky. Did you use Python as well?

**Comment by maelle** [comment]
I added this graph. Values are the same, I changed one of them for seeing the time shift. And one sees the plateaus (I'd tend to write this plateaux as in French :-) ) too. I found it interesting.

![oneday](https://cloud.githubusercontent.com/assets/8360597/12531454/59937512-c1fb-11e5-8d29-f535b88471df.png)
